- name: Ensure site "{{ virtualhost_domain }} " document root folder
  file: path="{{ virtualhost_document_root }}" state=directory

- name: Ensure virtualhost "{{ virtualhost_domain }} " log dir
  file: path="{{ virtualhost_logdir }}" state=directory owner="{{ caddy_user }}" mode=0750

- name: Virtualhost {{ virtualhost_domain }} | "{{ virtualhost_template }}"
  template: src="{{ virtualhost_template_file }}" dest="{{ caddy_etc_dir }}/sites/{{ virtualhost_domain }}.conf"
  notify: Reload caddy server
